### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lidan-ya** [taokz/FedR#1]
Hello author, is the work still going on, is the code updated? I found no commits for working code for safe aggregation

**Comment by taokz** [comment]
Hi, Thank you for reaching out. 

I am sorry that we do not plan to release the sec egg protocol because 1) it is not the key component in our implementation and it makes the experiments time-consuming. Most importantly, I would like to make the code easy to read. 2) there are many existing open-source codes you can refer to write your own codes.
